version: "3.9"

x-volumes: &volumes
  - ./jupyter:/app/jupyter
  - ./notebooks:/app/notebooks
  - ./docker/services:/app/services
  - /var/run/docker.sock:/var/run/docker.sock
  - jupyter-app:/opt/conda/share/jupyter
  - jupyter-user:/home/jovyan/.jupyter

x-environment: &environment
  - DOCKERHUB_USER
  - DOCKERHUB_TOKEN
  - GITHUB_REF
  - GITHUB_USER
  - GITHUB_TOKEN

x-base: &base
  image: ystk-jupyterlab
  build: .
  volumes: *volumes

services:
  shell:
    <<: *base
    entrypoint: ["bash"]
    user: root
    environment: *environment
    profiles:
      - none
      
  jupyterlab:
    <<: *base
    entrypoint: ["bash", "/app/services/jupyterlab.sh"]
    ports:
      - 8888:8888

  deploy:
    <<: *base
    entrypoint: ["bash", "/app/services/deploy.sh"]
    environment: *environment
    profiles:
      - none

  pull:
    image: docker
    entrypoint: ["sh", "/app/services/pull.sh"]
    volumes: *volumes
    environment: *environment
    profiles:
      - none

volumes:
  jupyter-app:
  jupyter-user:
