
version: "3.9"

services:
  jupyterlab:
    ports:
      # 接続ポートの追加 e.g. localhost:10080
      - 10080:8888
    volumes:
      # 任意のディレクトリをルートにして Jupyter を起動
      # ./jupyter/jupyter_notebook_config.py
      # c.NotebookApp.notebook_dir = '/home/user'
      - ~:/home/user
  
  selenoid:
    image: aerokube/selenoid:latest
    container_name: ystk-jupyterlab-selenoid
    restart: always
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenium/selenoid/config:/etc/selenoid:ro
      - ./selenium/selenoid/video:/opt/selenoid/video/
      - ./selenium/selenoid/logs:/opt/selenoid/logs/
    command: >
      -conf /etc/selenoid/browsers.json
      -video-output-dir /opt/selenoid/video
      -log-output-dir /opt/selenoid/logs
      -container-network ystk-jupyterlab_default
    healthcheck:
      test: ["CMD-SHELL", "stat /opt/selenoid/logs/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: ystk-jupyterlab-selenoid-ui
    depends_on:
      - selenoid
    restart: always
    ports:
      - 8080:8080
    command: ["--selenoid-uri", "http://ystk-jupyterlab-selenoid:4444"]
