version: "3.9"

x-volumes: &volumes
  - ./docker/services:/services
  - ./jupyter:/home/jovyan/.jupyter
  - jupyter-app:/opt/conda/share/jupyter
  - ./notebooks:/notebooks
  - /var/run/docker.sock:/var/run/docker.sock

x-base: &base
  image: ystk-jupyterlab
  container_name: ystk-jupyterlab
  build: .
  volumes: *volumes

services:
  shell:
    <<: *base
    entrypoint: ["bash"]
    user: root
    profiles:
      - none
      
  jupyterlab:
    <<: *base
    entrypoint: ["start-notebook.sh"]
    ports:
      - 8888:8888

  deploy:
    <<: *base
    entrypoint: ["bash", "/services/deploy.sh"]
    environment:
      - GITHUB_REF
      - GITHUB_TOKEN

volumes:
  jupyter-app:
