version: "3.9"

x-volumes: &volumes
  - ./jupyter:/app/jupyter
  - ./notebooks:/app/notebooks
  - ./docker/services:/app/services
  - /var/run/docker.sock:/var/run/docker.sock
  - jupyter-app:/opt/conda/share/jupyter/lab
  - jupyter-user:/home/jovyan/.jupyter

x-environment: &environment
  - DOCKERHUB_USER
  - DOCKERHUB_TOKEN
  - GITHUB_REF
  - GITHUB_USER
  - GITHUB_TOKEN

x-base: &base
  image: ystk-jupyterlab
  container_name: ystk-jupyterlab
  working_dir: /app/services
  build:
    context: docker/setup
    dockerfile: ../../Dockerfile
  user: root
  volumes: *volumes

services:
  shell:
    <<: *base
    entrypoint: ["bash"]
    environment: *environment
    profiles:
      - none
      
  jupyterlab:
    <<: *base
    user: jovyan
    entrypoint: ["bash", "jupyterlab.sh"]
    ports:
      - 8888:8888

  deploy:
    <<: *base
    entrypoint: ["bash", "deploy.sh"]
    environment: *environment
    profiles:
      - none

  pull:
    image: docker
    entrypoint: ["sh", "pull.sh"]
    volumes: *volumes
    environment: *environment
    profiles:
      - none

volumes:
  jupyter-app:
  jupyter-user:
